version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: ./config/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./web:/var/www/html
      - ./config/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - db
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "rootpassword"
      MYSQL_DATABASE: "webapp"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
    volumes:
      - db_data:/var/lib/mysql
      - ./config/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data: