version: '3.8'
services:
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./web:/var/www/html
    depends_on:
      - db
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "rootpassword"
      MYSQL_DATABASE: "webapp"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: